server:
  port: 8091
  tomcat:
    max-threads: 300
    accept-count: 100
    max-connections: 10000

spring:
  application:
    name: huida-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #Nacos地址
  datasource:
    url: jdbc:mysql://localhost:3306/huida?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


dubbo:
  application:
    id: dubbo-starter-consumer
    name: dubbo-starter-consumer
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: huida-service



mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml


jwt:
  secret: secret
  expiration: 7200000
  token: Authorization
feign:
  hystrix:
    enabled: true
