spring:
  application:
    name: huida-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8091


dubbo:
  application:
    id: dubbo-starter-consumer
    name: dubbo-starter-consumer
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: huida-service

