server:
  port: 9090
eureka:
  instance:
    hostname: 127.0.0.1
    #instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random .value}}}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka-service